# Generated by Django 2.1 on 2018-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('GOOD', 'GOOD'), ('BAD', 'BAD'), ('WORST', 'WORST')], max_length=200)),
                ('audibility', models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('GOOD', 'GOOD'), ('BAD', 'BAD'), ('WORST', 'WORST')], max_length=200)),
                ('clarity', models.CharField(choices=[('EXCELLENT', 'EXCELLENT'), ('GOOD', 'GOOD'), ('BAD', 'BAD'), ('WORST', 'WORST')], max_length=200)),
                ('partiality', models.CharField(choices=[('NO PARTIALITY', 'NO PARTIALITY'), ('SOMETIMES', 'SOMETIMES'), ('ALL THE TIME', 'ALL THE TIME')], max_length=200)),
                ('homework', models.CharField(choices=[('NO HOMEWORKS', 'NO HOMEWORKS'), ('SOMETIMES', 'SOMETIMES'), ('REGULARLY', 'REGULARLY')], max_length=200)),
                ('punctuality', models.CharField(choices=[('NEVER LATE', 'NEVER LATE'), ('OCCASIONALLY LATE', 'OCCASIONALLY LATE'), ('ALWAYS LATE', 'ALWAYS LATE')], max_length=200)),
                ('another_class', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
